### ISSUE TITLE
Configuration of client certificate options

### ISSUE THREAD

**Issue by carey-bishop** [natemcmaster/LettuceEncrypt#100]
**Is your feature request related to a problem? Please describe.**
Kestrel [does not seem to provide a configuration file-based approach](https://github.com/dotnet/aspnetcore/issues/18660) for setting the defaults for HTTPS endpoints. As such, the recommended approach is to [call ConfigureKestrel then ConfigureHttpsDefaults to enable client certificate support](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.1#configure-your-host-to-require-certificates). However, this seems to override the [KestrelOptionsSetup class](https://github.com/natemcmaster/LettuceEncrypt/blob/master/src/LettuceEncrypt/Internal/KestrelOptionsSetup.cs) that is registered by LettuceEncrypt. As such, automatic certificate selection and TLS ALPN challenges are not supported when client certificates are enabled.

There does not appear to be a way to chain multiple calls to ```ConfigureHttpsDefaults```, as it's stored in a single [HttpsDefaults](https://github.com/aspnet/KestrelHttpServer/blob/master/src/Kestrel.Core/KestrelServerOptions.cs#L82) property on ```KestrelServerOptions```. Only the last ```Action``` provided to ```ConfigureHttpsDefaults``` will be used, the others are silently ignored.

There is also no way to manually invoke the LettuceEncrypt options afterwards, as the three classes involved are internal (```KestrelOptionsSetup```, ```TlsAlpnChallengeResponder``` & ```CertificateSelector```), 

**Describe the solution you'd like**
Possible solutions include:
- A way to register another ```Action``` or class to be called from ```KestrelOptionsSetup``` after LettuceEncrypt has configured its own settings, eg:

```csharp
services.AddLetsEncrypt(o => {
  o.ConfigureHttpsDefaults(h => {
    h.ClientCertificateMode = ClientCertificateMode.RequireCertificate;
    h.ClientCertificateValidation = MyValidationMethod;
  }
});
```

- A public extension method in LettuceEncrypt linked to ```HttpsConnectionAdapterOptions``` that can manually be called to configure LettuceEncrypt if ConfigureHttpsDefaults needs to be invoked from the calling application, eg:

```csharp
public void Configure(KestrelServerOptions options) {
  options.ConfigureHttpsDefaults(o => {
    o.ClientCertificateMode = ClientCertificateMode.RequireCertificate;
    o.ClientCertificateValidation = MyValidationMethod;
    o.AddLettuceEncrypt();
  }
}
```

**Describe alternatives you've considered**
1. We can use code to enable client certificates then manually specify the SSL server certificate to use in appsettings.json. This does not invoke ```KestrelOptionsSetup```, so does not support TLS ALPN challenges, and requires a lot of configuration (eg: domain names need to be listed in multiple places in the JSON file for both Kestrel & LettuceEncrypt to use).

2. ```IConfigureOptions<T>``` is not used for ```HttpsConnectionAdapterOptions``` by Kestrel, which prevents [that pattern from being used to register multiple providers](https://stevetalkscode.co.uk/using-iconfigureoptions) to configure those options. However, I've created a hacky workaround by registering a class that implements ```IConfigureOptions<KestrelServerOptions>```. It uses reflection to get the previous value of the ```HttpsDefaults``` private property on ```KestrelServerOptions``` so that we can call ```ConfigureHttpsDefaults```, invoke the previous callback then set the new properties that we want. However, this is a fragile workaround as it is dependent on private APIs.

**Comment by natemcmaster** [comment]
@carey-bishop I couldn't find a way to fix this without requiring new API and you to add additional configuration to your code. I've opened a PR to implement the second option you described, #109. Usage would look like this:

https://github.com/natemcmaster/LettuceEncrypt/blob/383fab75e9941daf162b9afa42ff091061e567c4/samples/Web/Program.cs#L26-L34

Would appreciate feedback. 

At the same time, it might be nice to ask the aspnetcore team to make this easier to do with dependency injection. If that becomes an option in .NET 5 or later, we could update this library to take advantage of that.

**Comment by Tratcher** [comment]
> At the same time, it might be nice to ask the aspnetcore team to make this easier to do with dependency injection

Like making HttpsDefaults into a list of callbacks so you could call ConfigureHttpsDefaults multiple times for cumulative effect?

**Comment by natemcmaster** [comment]
That, or `IOptions<HttpsConnectionAdapterOptions>` so you can use your regular `IConfigureOptions` and `IPostConfigureOptions` interfaces to build up a cumulative effect.

**Comment by natemcmaster** [comment]
PR auto-closed. Re-opening until this is released with 1.1.0. Still open to feedback.

**Comment by AraHaan** [comment]
From the PR:

Oh nice thanks, oh and btw this Middleware automatically renews said certs?

I been looking for something where I would not have to worry about doing certs or having to be forced to restart my kestrel webapi I host myself and got exposed to public internet. Which would be a pain of itself tbh.

**Comment by natemcmaster** [comment]
@AraHaan your comment seems a little off topic. Maybe I misunderstood, but I'm not sure if this is relevant in this thread. Can you create a new issue if you have general questions about this project? This issue is about addressing an issue with chaining `ConfigureHttpsDefaults` API calls.

**Comment by carey-bishop** [comment]
Thanks @natemcmaster, the new API seems to work well.

As you mention, use of the ```IOptions<HttpsConnectionAdapterOptions>``` pattern in Kestrel would be a much nicer approach, but this works just fine.

**Comment by natemcmaster** [comment]
I'm going to release 1.1.0 today. Thanks for your patience with this project.
