### ISSUE TITLE
Can I use LettuceEncrypt with Kubernetes?

### ISSUE THREAD

**Issue by Almeonamy** [natemcmaster/LettuceEncrypt#102]
I deployed ASP.NET Core app to Kubernetes. Can I use LettuceEncrypt? I don't want use nginx reverse proxy.

**Comment by natemcmaster** [comment]
Sort of. Have you read this discussion https://github.com/natemcmaster/LettuceEncrypt/issues/79? You could probably make things work, but we're still working on finding the right abstractions for distributed apps that need SSL termination on multiple nodes and also want certificate renewal/generation automation.
