### ISSUE TITLE
Support for Staging Environment 

### ISSUE THREAD

**Issue by iAmBipinPaul** [natemcmaster/LettuceEncrypt#117]
I tired to use this using docker and just after trying few times I started getting rate limit error.
much better if we will have option to switch between staging API and Production API.

References 
https://acme-staging-v02.api.letsencrypt.org/directory
https://letsencrypt.org/docs/staging-environment/

**Comment by natemcmaster** [comment]
Already supported. https://github.com/natemcmaster/LettuceEncrypt/blob/b9ec34c69ed4043e81a3763dcac41db6f589db41/samples/Web/appsettings.Staging.json#L1-L8

**Comment by iAmBipinPaul** [comment]
Oh sorry,  I didn't see that.
