### ISSUE TITLE
How can it be used in Google App Engine with microservices?

### ISSUE THREAD

**Issue by TomasWeg** [natemcmaster/LettuceEncrypt#128]
I'm planning to deploy an infrastructure of microservices to Google App Engine and only my API Gateway will have my domain pointed to its IP. For the microservices communication, I will use gRPC without any domain. It's possible to attach an SSL certificate'

**Comment by natemcmaster** [comment]
I don't know anything about Google's hosting platform. Can you identify if it falls under one of these scenarios? https://github.com/natemcmaster/LettuceEncrypt/wiki/Will-this-work-for-me%3F#web-server-scenarios
