### ISSUE TITLE
[Question] Failed to validate ownership of domainName

### ISSUE THREAD

**Issue by chukaif** [natemcmaster/LettuceEncrypt#140]
Automatic certificate generation failed. How can I solve this problem?
Here is the error log:
2020/09/03 17:50:47.519|ERROR|Failed to validate ownership of domainName 'dir.yqeet.net'. Reason: urn:ietf:params:acme:error:unauthorized: Invalid response from http://dir.yqeet.net/.well-known/acme-challenge/NybEPLpXB1qe2jMYK_ER_TelEMUtrtecRtA_Y2tFzOY [106.55.45.112]: "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n<html xmlns=\"http", Code = Forbidden 

2020/09/03 17:50:47.530|ERROR|Failed to automatically create a certificate for dir.yqeet.net Failed to validate ownership of domainName 'dir.yqeet.net'

2020/09/03 17:50:47.693|ERROR|ACME state machine encountered unhandled error Failed to validate ownership of domainName 'dir.yqeet.net'

**Comment by natemcmaster** [comment]
Your server is using IIS. This falls under this category of unsupportable scenarios: https://github.com/natemcmaster/LettuceEncrypt#aspnet-core-with-iis. 
```
$ curl -i  http://dir.yqeet.net
HTTP/1.1 403 Forbidden
Content-Type: text/html
Server: Microsoft-IIS/10.0                          <----- see here
Date: Fri, 04 Sep 2020 05:39:42 GMT
Content-Length: 1233
```

You will need to use another project which supports IIS. Sorry, not much I can do here as IIS is fundamentally different from Kestrel.

**Comment by chukaif** [comment]
ok,i see. Thank you for your reply!
If I use kestrel to run a Asp.Net Core program, and listen to port 80, Can it solve the problem?

**Comment by chukaif** [comment]
> Your server is using IIS. This falls under this category of unsupportable scenarios: https://github.com/natemcmaster/LettuceEncrypt#aspnet-core-with-iis.
> 
> ```
> $ curl -i  http://dir.yqeet.net
> HTTP/1.1 403 Forbidden
> Content-Type: text/html
> Server: Microsoft-IIS/10.0                          <----- see here
> Date: Fri, 04 Sep 2020 05:39:42 GMT
> Content-Length: 1233
> ```
> 
> You will need to use another project which supports IIS. Sorry, not much I can do here as IIS is fundamentally different from Kestrel.

ok,i see. Thank you for your reply!
If I use kestrel to run a Asp.Net Core program, and listen to port 80, Can it solve the problem?

**Comment by natemcmaster** [comment]
Yes.

**Comment by chukaif** [comment]
> Yes.

I succeeded at last.

The program needs to listen to port 80 of HTTP and another port for HTTPS at the same time, so that it can succeed.

thank you!
