### ISSUE TITLE
[Question] No such challenge

### ISSUE THREAD

**Issue by chukaif** [natemcmaster/LettuceEncrypt#141]
hi, I'm having a new problem on another server.
this is the logs...

2020/09/10 11:32:01.465|INFO|Using certificate authority https://acme-v02.api.letsencrypt.org/directory 
2020/09/10 11:32:01.474|TRACE|ACMEv2 action: FetchAccount 
2020/09/10 11:32:03.194|TRACE|ACMEv2 action: FetchAccountDetails, https://acme-v02.api.letsencrypt.org/acme/acct/96248506 
2020/09/10 11:32:03.439|INFO|Using existing account for mailto:developer@yqeet.net 
2020/09/10 11:32:03.451|TRACE|ACMEv2 action: FetchTOS 
2020/09/10 11:32:03.451|TRACE|Terms of service has been accepted per configuration options 
2020/09/10 11:32:03.451|TRACE|ACMEv2 action: UpdateTOS 
2020/09/10 11:32:03.809|INFO|Using account 96248506 
2020/09/10 11:32:03.816|INFO|Creating certificate for dlh.yqeet.net 
2020/09/10 11:32:03.816|TRACE|ACMEv2 action: FetchOrderList 
2020/09/10 11:32:04.110|TRACE|ACMEv2 action: FetchOrderDetails, (null) 
2020/09/10 11:32:04.110|DEBUG|Creating new order for a certificate 
2020/09/10 11:32:04.110|TRACE|ACMEv2 action: NewOrder 
2020/09/10 11:32:05.226|TRACE|ACMEv2 action: FetchAuthorizations, https://acme-v02.api.letsencrypt.org/acme/order/96248506/5110176192 
2020/09/10 11:32:05.499|TRACE|ACMEv2 action: FetchAuthorizationDetails, https://acme-v02.api.letsencrypt.org/acme/authz-v3/7112297697 
2020/09/10 11:32:05.766|DEBUG|Requesting authorization to create certificate for dlh.yqeet.net 
2020/09/10 11:32:05.766|TRACE|ACMEv2 action: CreateChallenge, https://acme-v02.api.letsencrypt.org/acme/authz-v3/7112297697 
2020/09/10 11:32:06.010|TRACE|Creating ALPN self-signed cert for dlh.yqeet.net and key authz PvZGYiZ1tWGMymHMck2SjlvES-mDsnrKYiKkzUyQ-FI.bNrQWKDrBvRkDdzkdExohAcofvJSHV0hpm4g0-Lr480 
2020/09/10 11:32:06.283|TRACE|Waiting for server to start accepting HTTP requests 
2020/09/10 11:32:06.283|TRACE|Requesting server to validate TLS/ALPN challenge 
2020/09/10 11:32:06.283|TRACE|ACMEv2 action: ValidateChallenge, https://acme-v02.api.letsencrypt.org/acme/chall-v3/7112297697/uro_Mg 
2020/09/10 11:32:06.562|TRACE|ACMEv2 action: CreateChallenge, https://acme-v02.api.letsencrypt.org/acme/authz-v3/7112297697 
2020/09/10 11:32:06.800|TRACE|Waiting for server to start accepting HTTP requests 
2020/09/10 11:32:06.800|TRACE|Requesting server to validate HTTP challenge 
2020/09/10 11:32:06.815|TRACE|ACMEv2 action: ValidateChallenge, https://acme-v02.api.letsencrypt.org/acme/chall-v3/7112297697/QRMdpQ 
2020/09/10 11:32:07.807|ERROR|Failed to automatically create a certificate for dlh.yqeet.net Fail to load resource from 'https://acme-v02.api.letsencrypt.org/acme/chall-v3/7112297697/QRMdpQ'.
urn:ietf:params:acme:error:malformed: No such challenge
2020/09/10 11:32:07.830|ERROR|ACME state machine encountered unhandled error Fail to load resource from 'https://acme-v02.api.letsencrypt.org/acme/chall-v3/7112297697/QRMdpQ'.
urn:ietf:params:acme:error:malformed: No such challenge

**Comment by fjod** [comment]
I tried following test routine and got same issue:

"C:\Program Files\JetBrains\JetBrains Rider 2020.2.2\lib\ReSharperHost\JetBrains.Debugger.Worker64c.exe" --mode=client --frontend-port=52999 --plugins=
info: LettuceEncrypt.Internal.AcmeClient[0]
      Using certificate authority https://acme-staging-v02.api.letsencrypt.org/directory
info: LettuceEncrypt.Internal.AcmeCertificateFactory[0]
      Creating new account for **xxxxyyyyzzzzz@testtest@com  (used my good email here)**
info: LettuceEncrypt.Internal.AcmeStates.ServerStartupState[0]
      Using account 15744035
info: LettuceEncrypt.Internal.AcmeStates.ServerStartupState[0]
      Creating certificate for e3e072369225.ngrok.io
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\study\crawler\API
fail: LettuceEncrypt.Internal.AcmeStates.ServerStartupState[0]
      Failed to automatically create a certificate for e3e072369225.ngrok.io
Certes.AcmeRequestException: Fail to load resource from 'https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/116089247/qGKXCg'.
urn:ietf:params:acme:error:malformed: No such challenge
   at Certes.Acme.IAcmeHttpClientExtensions.Post[T](IAcmeHttpClient client, Uri uri, Object payload, Boolean ensureSuccessStatusCode)
   at Certes.Acme.ChallengeContext.Validate()
   at LettuceEncrypt.Internal.AcmeClient.ValidateChallengeAsync(IChallengeContext httpChallenge)
   at LettuceEncrypt.Internal.AcmeCertificateFactory.PrepareHttpChallengeResponseAsync(IAuthorizationContext authorizationContext, String domainName, CancellationToken cancellationToken)
   at LettuceEncrypt.Internal.AcmeCertificateFactory.ValidateDomainOwnershipAsync(IAuthorizationContext authorizationContext, CancellationToken cancellationToken)
   at LettuceEncrypt.Internal.AcmeCertificateFactory.CreateCertificateAsync(CancellationToken cancellationToken)
   at LettuceEncrypt.Internal.AcmeStates.BeginCertificateCreationState.MoveNextAsync(CancellationToken cancellationToken)
fail: LettuceEncrypt.Internal.AcmeCertificateLoader[0]
      ACME state machine encountered unhandled error
Certes.AcmeRequestException: Fail to load resource from 'https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/116089247/qGKXCg'.
urn:ietf:params:acme:error:malformed: No such challenge
   at Certes.Acme.IAcmeHttpClientExtensions.Post[T](IAcmeHttpClient client, Uri uri, Object payload, Boolean ensureSuccessStatusCode)
   at Certes.Acme.ChallengeContext.Validate()
   at LettuceEncrypt.Internal.AcmeClient.ValidateChallengeAsync(IChallengeContext httpChallenge)
   at LettuceEncrypt.Internal.AcmeCertificateFactory.PrepareHttpChallengeResponseAsync(IAuthorizationContext authorizationContext, String domainName, CancellationToken cancellationToken)
   at LettuceEncrypt.Internal.AcmeCertificateFactory.ValidateDomainOwnershipAsync(IAuthorizationContext authorizationContext, CancellationToken cancellationToken)
   at LettuceEncrypt.Internal.AcmeCertificateFactory.CreateCertificateAsync(CancellationToken cancellationToken)
   at LettuceEncrypt.Internal.AcmeStates.BeginCertificateCreationState.MoveNextAsync(CancellationToken cancellationToken)
   at LettuceEncrypt.Internal.AcmeCertificateLoader.ExecuteAsync(CancellationToken stoppingToken)

**Comment by bordenit** [comment]
Did you try changing port to port 80 and 443?

**Comment by chukaif** [comment]
> Did you try changing port to port 80 and 443?

I used 80 port for http，another port (not 443) for https, this worked on one server, but failed on another server. i don't know 'No such challenge' mean

**Comment by SebastianStehle** [comment]
I have the same problem. I tested it locally with ngrok and also on a remote server.

**Comment by Fydar** [comment]
I'm getting the same issue. I'm going to spend some time debugging, trying different ports and checking my firewalls and DNS configuration, e.t.c

I see that @fjod's application has ports open on 5000 and 5001, which makes me think that your issue might be due to a failed HTTP challenge which requires your application to listen on port 80.

**Comment by chukaif** [comment]
> I'm getting the same issue. I'm going to spend some time debugging, trying different ports and checking my firewalls and DNS configuration, e.t.c
> 
> I see that @fjod's application has ports open on 5000 and 5001, which makes me think that your issue might be due to a failed HTTP challenge which requires your application to listen on port 80.

thanks for reply,  i tried 80 port for http, but it's failed.

**Comment by natemcmaster** [comment]
Sorry for long delays on responses. I am merging a refactor of domain validation. It has been really hard to test and reproduce these kinds of errors, but I think I found an important thing this library was doing wrong. The fix should be in the 1.1.0 version of this library, which I intended to release soon. Please give the updated and open an new issue if you still have errors.
