### ISSUE TITLE
Getting "Some services are not able to be constructed" using the sample app

### ISSUE THREAD

**Issue by bar10dr** [natemcmaster/LettuceEncrypt#145]
I was in the process of integrating LettuceEncrypt in my own project using the sample app as a guide.
Kept getting a "Some services are not able to be constructed" error on CreateHostBuilder(args).Build().Run();

I cloned the main sample app and ran it, and I get the same error there.

```
InvalidOperationException: Error while validating the service descriptor 'ServiceType: LettuceEncrypt.Internal.AcmeCertificateFactory Lifetime: Singleton ImplementationType: LettuceEncrypt.Internal.AcmeCertificateFactory': Unable to resolve service for type 'LettuceEncrypt.Accounts.IAccountStore' while attempting to activate 'LettuceEncrypt.Internal.AcmeCertificateFactory'.


InvalidOperationException: Unable to resolve service for type 'LettuceEncrypt.Accounts.IAccountStore' while attempting to activate 'LettuceEncrypt.Internal.AcmeCertificateFactory'.
```

![image](https://user-images.githubusercontent.com/842487/95121324-305acd00-074f-11eb-8d6a-d8ff3cddfa17.png)

Obviously I'm doing something wrong here, any help would be appreciated.

**Comment by stigrune** [comment]
Duplicate. Check this workaround: https://github.com/natemcmaster/LettuceEncrypt/issues/132#issuecomment-717624172
