### ISSUE TITLE
Retry to create the certificate

### ISSUE THREAD

**Issue by SebastianStehle** [natemcmaster/LettuceEncrypt#149]
Hi, 

Usually when deploying an application the flow is like this:

1. Create server
2. Create DNS entry
3. Verify DNS entry
4. Deploy application.

I am thinking about building a azure template for my headless CMS. I am not 100% sure yet how https works in azure, but one good candidate is this library. The problem when creating containers and services with azure or other cloud providers is, that you do not know the IP in advance.

So the flow is like this:

1. Create server
2. Deploy application
3. Create DNS entry.

Another problem is when you have deploy the application and you have an error the next start of the application requires you to clear your state (account). At least it was the issue I had.

**Describe the solution you'd like**
The initial state should retry to create the certificate until it completes (or some time has passed).

**Describe alternatives you've considered**
I don't think that there is a good alternative right now.

**Comment by natemcmaster** [comment]
This seems reasonable to me. Applying the "help wanted" label as this is something I would accept a pull request for, but don't have plans to implement this myself. There aren't any other active developers on this project right now, but if you're (future reader) are reading this comment and want to help implement, please make a comment here so others know you're going to begin implementation.
