### ISSUE TITLE
How to set more properties in cert signing request? 

### ISSUE THREAD

**Issue by VoIPTools** [natemcmaster/LettuceEncrypt#150]
I am a novice.  The defaults work perfectly, but should I also be setting other properties such as the following?

- Common Name
- Organization
- Organizational Unit
- City/Locality, State
- County/Region, Country

What about Let's Encrypt settings including:

- When to attempt to renew (30 days before expiry)
- Use Staging: true/false 

Maybe more properties just add unnecessary complexity?

**Comment by natemcmaster** [comment]
he other properties you mention...Org, City, Country, etc...are not supported by Let's Encrypt. I looked into this in #8 and it's not possible. See https://letsencrypt.org/docs/faq/#will-let-s-encrypt-issue-organization-validation-ov-or-extended-validation-ev-certificates. If you need a cert that has those properties, you will need to use a different certificate authority.

You should already be able to control renewal settings and staging/non-staging.. See https://github.com/natemcmaster/LettuceEncrypt/blob/v1.0.0/src/LettuceEncrypt/LettuceEncryptOptions.cs
