### ISSUE TITLE
LettuceEncryptKestrelHttpsOptionsExtensions.cs missing in NuGet package build version 1.0.1 and 1.0.0

### ISSUE THREAD

**Issue by MentalAllergen** [natemcmaster/LettuceEncrypt#165]
**Describe the bug**
The 1.0.1 and 1.0.0. versions of the NuGet packages seem to be build from source code which doesn't include the LettuceEncryptKestrelHttpsOptionsExtensions.cs with the HttpConnectionAdapterOptions extension method as showcased by this [link](https://github.com/natemcmaster/LettuceEncrypt/tree/a871f3f825c0db0a30bad0dec8648a060bbcd38f) which is available on the NuGet Gallery of the package.

**To Reproduce**
1. Using the 1.0.1 or 1.0.0 version of the package
2. Try to build a clean app with a call to .UseKestrel() and .UseLettuceEncrypt(IServiceProvider)
3. Build fails with compiler arguing that the requested extension method does not exist

The workaround I've used is to install any of the two pre-release version available on NuGet as they have the file with the extension method present in their source code. For anyone stumbling on this and wondering how to install pre-release versions of packages using NuGet, read [this](https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages).

I'm happy to stay on the pre-relase package verision, but I think many will hit this hurdle when they try using this package and the workaround isn't all that intuitive.

**Comment by natemcmaster** [comment]
Yes, that will get fixed in the 1.1.0 release. In the meantime, use the pre-release versions from nuget.org.

**Comment by densen2014** [comment]
use the pre-release versions from nuget.org

**Comment by natemcmaster** [comment]
1.1.0 is released now, by the way.
