### ISSUE TITLE
Arbitrary CA Servers

### ISSUE THREAD

**Issue by LuvForAirplanes** [natemcmaster/LettuceEncrypt#166]
While I realize that the project was named LettuceEncrypt, which directly implies it is for use with Let's Encrypt, I would like to consider adding support for arbitrary CA servers. My goals for this are primarily in a development environment, but it may be useful in production also. (say, for an internal SSL network where we have a local CA authority)

This idea has been mentioned before: (Issue #50 Comment [629898104](https://github.com/natemcmaster/LettuceEncrypt/issues/50#issuecomment-629898104))
> So my point is, it would be nice to be able to fetch and use the latest cert from an **arbitrary ACME CA** or from a given http API endpoint...

What do ya'll think?

**Comment by gcelet** [comment]
Hi all,

I use [step-ca](https://github.com/smallstep/certificates) to manage my internal certificates: supporting arbitrary ACME CA would be super useful for me.

**Comment by LuvForAirplanes** [comment]
That's precisely what I'm using also.

**Comment by natemcmaster** [comment]
This should be possible already. Try providing your own implementation of `ICertificateAuthorityConfiguration` via DI. 
https://github.com/natemcmaster/LettuceEncrypt/blob/v1.0.1/src/LettuceEncrypt/Acme/ICertificateAuthorityConfiguration.cs

**Comment by LuvForAirplanes** [comment]
Thanks @natemcmaster I'll check into this. I had already implemented it a little differently, but I'll see if I can get my code modified.

**Comment by natemcmaster** [comment]
Closing as question is answered and this feature is already implemented.
