### ISSUE TITLE
[Question] Silly question - can this be used with Blazor Server-Side ?

### ISSUE THREAD

**Issue by devaale** [natemcmaster/LettuceEncrypt#190]
I know there's a whole explanation on the main page - which portrays if this can be used for a specified situation, however I'm too stupid to understand if this can be used with Blazor Server-Side web app or not ? - Simple Yes / No is enough for me, sorry for the useless question and appreciate any kind of answer in advance - cheeers ! <3

**Comment by Fydar** [comment]
Yes.

**Comment by devaale** [comment]
@Fydar Thank you <3
