### ISSUE TITLE
[Question] Anyone else gets "The remote certificate is invalid according to the validation procedure." on startup?

### ISSUE THREAD

**Issue by Memnarch** [natemcmaster/LettuceEncrypt#220]
Our service, while working fine for the past months, suddenly reports "The remote certificate is invalid according to the validation procedure." on startup. For somereason LettuceEcnrypt fails with this during the ACME-Challenge for LetsEncrypt.

Did anyone else run into this and knows how to fix it?

**Comment by Tratcher** [comment]
Their old root cert expired, you may need to update your machine.
https://scotthelme.co.uk/lets-encrypt-old-root-expiration/

**Comment by Memnarch** [comment]
Does .Net Core 3.1 come with their own openssl? Updating the OS does not help. It's CentOS 7(!). And I can't blacklist the outdated cert cause openssl is not installed on this machine.

**Comment by iAmBipinPaul** [comment]
Yes , same I'm facing this on Ubuntu . I updated machine  still facing same issue.

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
