### ISSUE TITLE
Nuget package not working

### ISSUE THREAD

**Issue by gromilQaaaa** [natemcmaster/LettuceEncrypt#233]
Hello,
I found this plugin and would like to use it because it is on forst pages of google. But apparently its nuget package is not usable, its just simply not visible by code. I even found an article where other person mentions the same problem.

The only solution by now is to download the project and put it directly into yours, but this approach just increases chances for this plugin to die. Maybe the reason is in missing namespace, or Microsoft changed something idk...

https://www.linkedin.com/pulse/how-get-free-lets-encrypt-certificates-net-core-docker-carlos-carre%C3%B1o?articleId=6619160196977688576

![image](https://user-images.githubusercontent.com/5392680/143584338-746682e8-5d73-4c0d-8c6e-84539e190292.png)

**Comment by natemcmaster** [comment]
You are probably missing a “using” statement.  Please see the samples and the README.md file for working examples of code.
