### ISSUE TITLE
Support certificate-per-domain

### ISSUE THREAD

**Issue by zakeryooo** [natemcmaster/LettuceEncrypt#236]
Hi,

I'm using LettuceEncrypt in a YARP project, the reverse proxy sends requests from https://domain1.com and https://domain2.com to separate web apps each using their own kestrel instances (localhost:5001, localhost:5005). 

Everything is working OK, but LettuceEncrypt is generating a single SSL certificate which covers both domains and instead I'm wanting it to generate a separate certificate for each domain, it's configured like this at the moment:

`"DomainNames": [ "domain1.com", "domain2.com" ],`

Is there a way to generate a certificate-per-domain instead of a single certificate for all domains?

Thanks

**Comment by natemcmaster** [comment]
This is not currently possible.

**Comment by zakeryooo** [comment]
Ok thanks, do you know if anyone else is working on this? I haven't had chance to look at the code yet be aware of how much work would be needed to add this, but if I get time to add it is it the sort of thing you'd accept a pull request for?

**Comment by natemcmaster** [comment]
I doubt anyone is working on this. The project is currently in maintenance mode (#189) so I'm not actively developing it, and there are aren't any other active contributors on this project. I'm not opposed to adding features, but even if someone else is implementing, it takes time for me to review, provide meaningful feedback, and then support the change for years to come.

I am not saying this to discourage you. I'm open to having other active contributors join this project who can pick up feature work and also provide support and bug fixes, but so long as I'm the only maintainer, I don't plan to accept new features.

**Comment by benschop-it** [comment]
I am also very much interested in certificate-per-domain functionality, and I'd be happy to work with someone (zakeryooo?) on this.

**Comment by natemcmaster** [comment]
Marking as <kbd>help wanted</kbd>. Let me know if you're interested in contributing this feature request.

**Comment by benschop-it** [comment]
I have implemented this feature in my fork at https://github.com/benschop-it/LettuceEncrypt-Archon.
This makes it possible to create a certificate per set of domains.
Some extra tests still need to be added.
Feel free to comment.
