### ISSUE TITLE
Conflicts with Certes => 3.0.0

### ISSUE THREAD

**Issue by drewek-smf** [natemcmaster/LettuceEncrypt#244]
Hi,

LettuceEncrypt seems to have issues with Certes >= 3.0.0, even though it's tagged to support >= 2.3.4.

Here's my log excerpt when using Certes 3.0.0:
`2022-03-25 13:29:39 [ERR] [LettuceEncrypt.Internal.AcmeStates.ServerStartupState] Failed to automatically create a certificate for "mydomain"
System.MissingMethodException: Method not found: 'Void Certes.AcmeContext..ctor(System.Uri, Certes.IKey, Certes.Acme.IAcmeHttpClient)'.`

The log looked similar when using latest Certes 3.0.3, unfortunately I already deleted it. But again a MissingMethodException came up, for `KeyFactory.NewKey()`, which got an additional Parameter.

With Certes 2.3.4 and latest LettuceEncrypt, everything is fine.

Regards, Michael Drewek

**Comment by natemcmaster** [comment]
Give version 1.2.0 a try. I updated the nuget dependency and haven't found any issues yet.
