### ISSUE TITLE
[Question]  .net 6 support

### ISSUE THREAD

**Issue by JYouren** [natemcmaster/LettuceEncrypt#253]
I know the nuget package doesn't support .net 6, but does the codebase support .net 6 if I build it myself?

**Comment by JYouren** [comment]
ok, as long as it actually works with .net 6, then I'm good. Thank you

**Comment by JYouren** [comment]
So did you compile as is, and then use the .net standard libraries, or did you attempt to uplift to .net 6?

**Comment by bugproof** [comment]
> So did you compile as is, and then use the .net standard libraries, or did you attempt to uplift to .net 6?

I just use the published nuget and works fine
