### ISSUE TITLE
Inaccurate docs

### ISSUE THREAD

**Issue by GioviQ** [natemcmaster/LettuceEncrypt#257]
In your readme I read

"IIS does not support dynamically configuring HTTPS certificates"

but I am using win-acme to do that

**Comment by natemcmaster** [comment]
Unless I'm mistaken, win-acme still requires admin privileges to configure IIS. The way LettuceEncrypt is fundamentally different -- it runs inside the web server process, which I would not recommend doing for your web server process.

Feel free to propose a PR to make the documentation more precise about why IIS can't be supported and reference win-acme as an alternative.
