### ISSUE TITLE
Only runs once, when I restart it doesnt run again.

### ISSUE THREAD

**Issue by 1FriendlyDoge** [natemcmaster/LettuceEncrypt#261]
I am using Blazor Server (.NET 6), whenever I am running it on Ubuntu (18.04). It only ran once, even when I remove all my app files and move them to my server again it doesnt generate any certificate (and logs nothing). Even the first time when it "worked", I couldn't connect to my web page at all.

Program.cs (only the important parts)
`builder.WebHost.UseKestrel(k =>
{
    var appServices = k.ApplicationServices;
    k.Listen(
        IPAddress.Any, 443,
        o => o.UseHttps(h =>
        {
            h.UseLettuceEncrypt(appServices);
        }));
});
builder.Services.AddLettuceEncrypt().PersistDataToDirectory(new DirectoryInfo(AppDomain.CurrentDomain.BaseDirectory + "Crypt/"), "PasswordHere");`

Is this a known issue or am I doing something wrong?

**Comment by natemcmaster** [comment]
I'm unable to reproduce the problem with the information provided. Please provide more steps to recreate this problem.
