### ISSUE TITLE
Certificate that support only TLS 1.2

### ISSUE THREAD

**Issue by defcore** [natemcmaster/LettuceEncrypt#268]
Is it possible to create a certificate that has only TLS 1.2 and no TLS 1.3?

**Comment by defcore** [comment]
I tried doing that by using:

`
.ConfigureWebHostDefaults(delegate (IWebHostBuilder webBuilder)
{
    webBuilder.UseKestrel(kestrelOptions =>
    {
        kestrelOptions.ConfigureHttpsDefaults(httpsOptions =>
        {
            httpsOptions.SslProtocols = SslProtocols.Tls12;
        });
    });
    webBuilder.UseStartup<Startup>();
})
`

But has no effect. When checking TLS versions I get TLS1.3 and TLS1.2.

Did I miss something?

**Comment by Tratcher** [comment]
UseKestrel -> ConfigureKestrel, but that shouldn't affect TLS.

How are you enabling LettuceEncrypt? Your ConfigureHttpsDefaults might be overwritten.
https://github.com/natemcmaster/LettuceEncrypt/issues/142#issuecomment-779396243
https://github.com/natemcmaster/LettuceEncrypt/blob/ffbd458c4ce030b7fdfb5b024daa7845687afc5c/src/LettuceEncrypt/Internal/KestrelOptionsSetup.cs#L24
