### ISSUE TITLE
Extending the configuration by "preferredChain"

### ISSUE THREAD

**Issue by JozefGulaPayius** [natemcmaster/LettuceEncrypt#274]
Our web site working properly, however, we are using MAUI application to connect to our web API service. Android devices have a problem with certificate verification for "DST Root CA X3". This root certificate is expired. The solution is to force "preferredChain: "ISRG Root X1"" for Let's encrypt, but this cannot be set in LettuceEncrypt.

https://github.com/xamarin/xamarin-android/issues/6351#issuecomment-936909856

https://learn.microsoft.com/en-us/answers/questions/573356/xamarin-android-ssl-error-connecting-to-signalr.html

Is it possible to extend configuration?

Thanks a lot

**Comment by natemcmaster** [comment]
I've just merged https://github.com/natemcmaster/LettuceEncrypt/pull/279. Can you take a look at this and see if it solves your problem?
