### ISSUE TITLE
Can't find issuer for staging server

### ISSUE THREAD

**Issue by FreeApophis** [natemcmaster/LettuceEncrypt#278]
* Bug #194 has never been adressed and no work-around has been documented.

A few questions to that:

1. Should adding the key to the key-store work? (We tried unsuccessfully)
2. Is there any other way to include the additional issuer? Certes has an AddIssuer, could that be exposed through LettuceEncrypt?
3. How do others work around this issue?

We would offer to make a PR fixing the issue, but we would like some pointers on how you would like it to be adressed.

**Comment by natemcmaster** [comment]
I've just merged https://github.com/natemcmaster/LettuceEncrypt/pull/279. Can you take a look at this and see if it solves your problem?

**Comment by FreeApophis** [comment]
Great, TY.
