### ISSUE TITLE
[Question] Certificates aren't persisted on disk

### ISSUE THREAD

**Issue by dadyarri** [natemcmaster/LettuceEncrypt#282]
I'm running application in linux docker container with this Lettuce's config on .net 7:

```csharp
builder.Services
        .AddLettuceEncrypt()
        .PersistDataToDirectory(
            new DirectoryInfo(builder.Configuration["Certificates:Path"]!),
            builder.Configuration["Certificates:Password"]
        );


    builder.WebHost.UseKestrel(k =>
    {
        var appServices = k.ApplicationServices;
        k.Listen(
            IPAddress.Any, 443,
            o => o.UseHttps(h =>
            {
                h.UseLettuceEncrypt(appServices);
            }));
    });
```

Account info are saved in specified location, whereas certificates doesn't:
![image](https://user-images.githubusercontent.com/51821039/215264389-452237b3-c107-4bad-806f-8d49408ea8be.png)

Because of it i'm exceeding certificates generation limit on production server each time i'm restarting application

What should i do to avoid it and reuse already generated certificates?

**Comment by TheDevelolper** [comment]
What was the solution?

**Comment by dadyarri** [comment]
> What was the solution?

I forgot to add a volume

**Comment by qcjxberin** [comment]
Without docker, it seems that there is no saving
