### ISSUE TITLE
My code signing cert expires soon, planning to drop code signatures on NuGet package

### ISSUE THREAD

**Issue by natemcmaster** [natemcmaster/LettuceEncrypt#71]
Hey all,

I used to get code-signing certs for free (perk of being a Microsoft employee.) I've lost that perk, so no more freebies. My current code-signing certificate expires in a few months. Once it does, I'm not planning to renew as [renewal is not cheap](https://www.digicert.com/code-signing/).

If this is a concern for you, we have until July 2020 to change course. As far as I can tell, though, no one really cares about code-signed NuGet packages (except the NuGet team and Microsoft.)

Alternatives to dropping code signing:
* help [sponsor](https://github.com/sponsors/natemcmaster) this project. I need a few sponsors to get enough to fund yearly renewals of the cert.
* help me find a code signing CA for free.
* if you are a CA reading this, consider being generous to open-source contributors like myself.

Please comment if you have concerns or suggestions.

**Comment by bordenit** [comment]
I hate the idea of anyone paying that much for a cert, but I just sponsored $10/month. There is value with this and it would suck if you just let this die.

**Comment by natemcmaster** [comment]
Thanks @bordenit! I appreciate the sponsorship. I've added your name to the list of sponsors on the readme for this page (so far, you're the first.)

I'm still looking for alternative code signing CAs. I'm finding lots of interesting stuff, but haven't found anything yet. It's too bad there isn't the equivalent of Let's Encrypt for code-signing. Maybe time to start "Let's Code Sign"?

**Comment by bordenit** [comment]
Looks like ACME would still need to be onboard with it. Found a draft here. Dell must want it too.
https://tools.ietf.org/html/draft-ietf-acme-client-00

**Comment by natemcmaster** [comment]
Turns out I'm going to have to rename this entire project (#84). As that's a massive breaking change, I'm going to drop code signing and start off with a new package that isn't authenticode signed. Based on feedback from Twitter and other GitHub conversations like https://github.com/natemcmaster/CommandLineUtils/issues/365, it seems like this should not impact most users.

In the future, if someone really needs my binaries and nupkg files authenticode signed, we can revisit.
