### ISSUE TITLE
Retrieving cert from Azure does not retrieve private key

### ISSUE THREAD

**Issue by Crypth** [natemcmaster/LettuceEncrypt#77]
After the the procedure of retrieving a certificate from LetsEncrypt is finished, it seems the X509CertStore stores the certificate locally under CurrentUser and if using Azure Keyvault storage, it also stores it there. Running the webserver locally works just fine after that, because loading the certificate from the local store retrieves the certificate with the private key. However, if you remove the certificate locally, the AzureKeyVaultCertificateRepository then retrieves the certificate by using a CertificateClient from the Azure keyvault. The problem is that this certificate does NOT include the private key and is thus useless to Kestrel for SSL binding. 

The solution is to add a SecretClient and retrieve the certifcate secret and parse it into a x509 certificate. 

I've written the solution and will send a pull request.

**Comment by natemcmaster** [comment]
Thanks for reporting. That seems like a bad problem. Let's get this fixed soon. Thanks for sending a pull request!
