### ISSUE TITLE
[Question]  Is it possible to add domains in runtime without restarting the app?

### ISSUE THREAD

**Issue by murbanowicz** [natemcmaster/LettuceEncrypt#83]
Is it possible to add domains in runtime without restarting the app?

I mean situation:
I have multiple domains pointing my app.
Users can add their domains.
I want to serve SSL for each domain if the request coming for a domain which was previously added

**Comment by natemcmaster** [comment]
Can you elaborate on your use case? Who are these users that are adding more domains? How are they updating DNS records?

If I understand right, this potentially needs to be split into two feature requests.

1. Add new domains after the server has started.
2. Request separate certificates for each domain. The current implementation requests one SSL cert and uses the Subject Alternative Name for additional domains, which could be problematic.

**Comment by alvaromarithompson** [comment]
We're also in a similar situation. We offer a "user portal" for our customers. The user portal is a single application, and the customer is able to configure within their account what the domain name for accessing the portal is.

The customer manages their own DNS, they have their own domain, and the way we function currently is they create a CNAME record for the sub-domain they wish to use (e.g. portal.domain.com) which then points to an A record on our own domain.

This way we're able to have the portal know which customer the user belongs to by the sub-domain in the configuration, and display the necessary information accordingly.

In this scenario, we need to have the ability to manually add a new certificate onto application, without restarting the application. The application will inevitably build a group of SSL certificats that will be needed, and more of these will be added on the fly as new customers come on board.

**Comment by bnssoftware** [comment]
Very much need this functionality as well.  We have a multitenant app which allows our customers to bring their own domain.  Could be:  theirdomain.com, app.theirdomain.com or *.theirdomain.com.  Either we host their domain for them, or they host domain and have a CNAME pointing to our DNS (AWS Route53).  We would need to use Letsencrypt HTTP challenge for these.

We would need to be able to add/remove these on the fly during runtime without any downtime.

**Comment by natemcmaster** [comment]
Added the help-wanted label. This means I'm open to accepting contributions for this, but don't have immediate plans to build this for you. Let me know if you are interested in submitting a pull request.
