### ISSUE TITLE
[Question] Can we specify where certificates are stored?

### ISSUE THREAD

**Issue by bnssoftware** [natemcmaster/LettuceEncrypt#87]
Since we are using AWS ECS with Docker containers, instances may come and go.  We want already downloaded certificates to survive this.  We are thinking to use EFS (Elastic File System) to store the certs outside the Docker containers to make them survive.   EFS is attached as a mount point.

Is this possible?

**Comment by andrewjsaid** [comment]
Hey, just found this repo today really but from what I can tell there is already an Azure Key Vault implementation, example here

https://github.com/natemcmaster/LettuceEncrypt/blob/master/samples/KeyVault/Startup.cs

The implementation is here:

https://github.com/natemcmaster/LettuceEncrypt/tree/master/src/LettuceEncrypt.Azure

Specifically I think you must implement two interfaces - `ICertificateRepository` and `ICertificateSource`

**Comment by natemcmaster** [comment]
Did you read the README doc?

**Comment by natemcmaster** [comment]
Updated the readme with more info about customizing this behavior.
