### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by natemcmaster** [natemcmaster/LettuceEncrypt#88]
I'm not a graphic designer. Anyone want to make a new logo for this package?

**Comment by Donistivanov** [comment]
Here are some ideas:

![image](https://user-images.githubusercontent.com/12190565/82766013-696e5280-9de9-11ea-8270-7a2863720543.png)

**Comment by mrtalhim** [comment]
This is what I could come up with,
![image](https://user-images.githubusercontent.com/43179527/82888863-196fc700-9f74-11ea-89d7-de057c772159.png)

**Comment by bordenit** [comment]
> This is what I could come up with,
> ![image](https://user-images.githubusercontent.com/43179527/82888863-196fc700-9f74-11ea-89d7-de057c772159.png)

That looks nice. Changing the colors to the typical Microsoft blues and purples may make it even more relevant to the use case.

**Comment by mrtalhim** [comment]
> That looks nice. Changing the colors to the typical Microsoft blues and purples may make it even more relevant to the use case.
> 
> Something that ties it to Kestrel/.NET

I tried different ways to implement those colors. imo the gradient one looks clean
![image](https://user-images.githubusercontent.com/43179527/82982780-167ae200-a019-11ea-8b1c-57f3fa322cac.png)![image](https://user-images.githubusercontent.com/43179527/82982717-efbcab80-a018-11ea-87be-5fd7d1e01543.png)![image](https://user-images.githubusercontent.com/43179527/82983499-673f0a80-a01a-11ea-89c1-36c18ef26ca4.png)

**Comment by Fydar** [comment]
Do you like the look of any of these? :)

I'm not a graphic designer either but I found this project quite helpful! I'd love to see it have an icon in my NuGet package list!

![lettuce-encrypt-icon](https://user-images.githubusercontent.com/19309165/97374695-ce563900-18b0-11eb-94c6-f65ac95d3ab3.png)
![lettuce-encrypt-icon-bg](https://user-images.githubusercontent.com/19309165/97374696-ceeecf80-18b0-11eb-9255-64e0e4f7753d.png)

**Comment by natemcmaster** [comment]
Thanks to all who made suggestions. I'm going to add @Fydar's suggestion to the project.

Thanks @Fydar! This looks great!

**Comment by Fydar** [comment]
That's awesome to see! :)

I've attached the source for the icon (.pptx) as well as it in SVG format (plus a CC0 waiver).

[lettuceencrypt-icon-src.zip](https://github.com/natemcmaster/LettuceEncrypt/files/5505734/lettuceencrypt-icon-src.zip)

**Comment by natemcmaster** [comment]
@Fydar thanks again! This icon will be used in the next update of the NuGet package.
