### ISSUE TITLE
TlsAlpnChallengeResponder disabled/enbabled option

### ISSUE THREAD

**Issue by Crypth** [natemcmaster/LettuceEncrypt#98]
In some conditions, cluster environments for instance, exchanging the self signed certificate is a lot more complicated than exchanging a token&response, perhaps this could be an optional way to verify the DNS name, even when running .NET Core 3+?

**Comment by natemcmaster** [comment]
If clustered environments is the main concern, could this be generalized with #79 ?  I don't think it would be any more challenging to exchange the TLS-ALPN-01 response data among nodes in a clustered environment than it would be to exchange HTTP-01 data.

Aside from clustered environments, is there any other reason to the TLS-ALPN-01 challenge should be disabled?

**Comment by Crypth** [comment]
Sure it could be joined with #79 .. the main difference is the ease which you can load the tokens on the fly, while the cert needs to be preloaded. Not sure if there are other reasons people would like to use the HTTP-01 instead, unless anyone comes up with a reason, I'll close it and reopen it if it comes up.
