### ISSUE TITLE
Upgrading to LettuceEncrypt 1.0.0 🥬 - package and code renames

### ISSUE THREAD

**Issue by natemcmaster** [natemcmaster/LettuceEncrypt#99]
This project has been renamed to **LettuceEncrypt**. This rename does not affect the features it offers or its function. This rename requires manual changes to your code to upgrade from older versions ([see instructions below](#how-to-upgrade)), but I expect the upgrade will be minimal effort on your part. This project still uses https://letsencrypt.org as the default certificate authority.

Earlier versions of this project are now unsupported. Please upgrade to [LettuceEncrypt 1.0.0](https://github.com/natemcmaster/LettuceEncrypt/releases/tag/v1.0.0). 
There will not be any updates to McMaster.AspNetCore.LetsEncrypt on nuget.org. I have hidden the old packages, but per nuget.org's policy, they are not deleted so existing users can continue to download it.

## Why rename?

Earlier versions of this package were named "McMaster.AspNetCore.LetsEncrypt", a name selected from combining my family name, the web framework for .NET Core, and the most widely used certificate authority that implements the ACME protocol, which is "Let's Encrypt®", of course. This was started as a hobby project years ago and I never thought the naming would be a problem. This project drew the attention of the Internet Security Research Group (ISRG)™️, which runs Let's Encrypt. They informed me last week that they considered my original project name a violation of their trademarks. As this code is not an official offering of ISRG and I want to support their efforts to run Let's Encrypt, I have complied with their request to rename the project.

So to be clear, this project is **not officially offered by ISRG and Let's Encrypt**, nor Microsoft and the ASP.NET Core project or Azure. This is still a hobby project of @natemcmaster and is available for use under the terms of the [Apache License 2.0](https://github.com/natemcmaster/LettuceEncrypt/blob/master/LICENSE.txt).

#### Step 1 - your .csproj file
Replace usage of the McMaster.AspNetCore.LetsEncrypt with LettuceEncrypt.
```diff
- <PackageReference Include="McMaster.AspNetCore.LetsEncrypt" Version="0.5.0" />
- <PackageReference Include="McMaster.AspNetCore.LetsEncrypt.Azure" Version="0.5.0" />
+ <PackageReference Include="LettuceEncrypt" Version="1.0.0" />
+ <PackageReference Include="LettuceEncrypt.Azure" Version="1.0.0" />
```

#### Step 2 - update appsettings.json
Use the "LettuceEncrypt" key now to configure options.

```diff
// appsettings.json
{
-    "LetsEncrypt": {
+    "LettuceEncrypt": {
        "AcceptTermsOfService": true,
        "DomainNames": [ "example.com", "www.example.com" ],
        "EmailAddress": "it-admin@example.com",
    }
}
```

#### Step 3 - update your C# files
Find and replace all references to the 'McMaster.AspNetCore.LetsEncrypt' namespace with 'LettuceEncrypt'.

```diff
- using McMaster.AspNetCore.LetsEncrypt;
+ using LettuceEncrypt;
```
Also, you may need to update to use new type names and methods. You should be able to find/replace the word 'LetsEncrypt' with 'LettuceEncrypt'.

```diff
    public void ConfigureServices(IServiceCollection services)
    {
-        services.AddLetsEncrypt();
+        services.AddLettuceEncrypt();
    }
```

**Comment by slater1** [comment]
I find their trademark claim petty and depressing. They've punished you for doing a good thing for them. It's also dubiously legal. Thousands of open source projects have trademarked names somewhere in them - e.g in the form of `Some.Project.Adapters.Android`. However I understand your wanting to avoid a headache. You selected and excellent substitute name.
